[package]
name = "kartina"
version = "0.1.0"
authors = ["Timothy Maloney <tmaloney@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
play = "0.5.3"
nannou = "0.16.0"
nix = "0.9.0"
